[package]
name = "blipclip"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
arboard = "3.6.1"
log = "0.4.29"
notify-rust = "4.16.0"
simplelog = "0.12.2"

[package.metadata.packager]
product-name = "BlipClip"
identifier = "com.blipclip.app"
before-packaging-command = "cargo build --release"

[[package.metadata.packager.binaries]]
path = "blipclip"
main = true

[[package.metadata.packager.file-associations]]
extensions = ["blipc"]
name = "BlipClip File"
description = "BlipClip clipboard transfer file"
