name: Package
on:
  push:
    branches: [main]

jobs:
  package-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: cargo-bins/cargo-binstall@main
      # - uses: Swatinem/rust-cache@v2

      - run: cargo binstall cargo-packager --no-confirm --locked

      - run: cargo packager --release
      
      - uses: actions/upload-artifact@v7
        with:
          name: blipclip-macos
          path: target/release/*.dmg
