name: Package
on:
  push:
    branches: [main]

jobs:
  package:
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact: "*.dmg"
          - os: windows-latest
            artifact: "*.exe"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: cargo-bins/cargo-binstall@main
      # - uses: Swatinem/rust-cache@v2

      - run: cargo binstall cargo-packager --no-confirm --locked

      - run: cargo packager --release

      - uses: actions/upload-artifact@v7
        with:
          name: blipclip-${{ matrix.os }}
          path: target/release/${{ matrix.artifact }}
